-- ===========================================================================
-- V1 - Baseline schema (Section 10.7)
--
-- This is the schema as it stood at the end of the ddl-auto=update era: every
-- table and column Hibernate had created in the live databases, frozen into
-- versioned SQL so that from here on the schema is a reviewed artefact instead
-- of a side effect of application start-up.
--
-- WHERE THIS TEXT CAME FROM
-- It was not typed out from the entity classes. It is Hibernate's own
-- `jakarta.persistence.schema-generation` output for the entities in
-- com.jobportal.domain, reformatted (one column per line, entity field order,
-- comments) but not otherwise changed. `BaselineSchemaTest` re-generates that
-- output on every build and compares the resulting schema against the schema
-- this file produces, so the two cannot drift apart unnoticed.
--
-- WHY IT RUNS UNCHANGED ON BOTH H2 AND POSTGRESQL
-- Hibernate's DDL for H2 and for PostgreSQL 14 turned out to differ in exactly
-- one respect: how an @Enumerated(EnumType.STRING) column is declared. H2 gets
-- a native `enum ('A','B')` column; PostgreSQL gets `varchar(n)` plus a check
-- constraint. Every other line - `bigint generated by default as identity`,
-- `varchar(n)`, `integer`, `boolean`, `timestamp(6)`, `date`, and the primary
-- key, unique and foreign key clauses - was byte-for-byte identical.
--
-- So this file uses the PostgreSQL form everywhere: `varchar(n)` with a check
-- constraint. That form is plain SQL:2003 and H2 accepts it without a
-- compatibility mode, which is why one migration directory serves both
-- databases rather than a `db/migration/{vendor}` split (see 10.7 for the
-- options that were weighed). It also means the local H2 database now has the
-- same column types as production instead of a near-miss, so a query that
-- works locally is a better promise about production than it used to be.
--
-- WHY THE ENUM VALUE LISTS ARE NOT A MAINTENANCE TRAP
-- A check constraint freezes the accepted values. Adding a constant to one of
-- the enums in com.jobportal.domain.enums therefore needs a migration that
-- drops and recreates the constraint - which is the point: today, under
-- ddl-auto=update, Hibernate silently does NOT update enum constraints
-- (Section 10.4's table says so), so the new constant fails at insert time on
-- a long-lived database with no warning anywhere. Section 10.7 shows the
-- recipe.
--
-- EXISTING DATABASES DO NOT RUN THIS FILE
-- Both the hosted Render PostgreSQL database and a developer's ./data/jobportal
-- H2 file already contain every one of these tables, built by ddl-auto=update
-- and full of rows. spring.flyway.baseline-on-migrate=true makes Flyway adopt
-- such a database: it records V1 as already applied and starts work at V2.
-- This file only ever executes against an empty database.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- users - one account per person, whatever the role (Section 5.2, D-6).
-- Employers keep their company details here instead of in a separate profile
-- entity, which is why the three company_* columns are nullable: they are only
-- filled in for role = 'EMPLOYER'.
-- ---------------------------------------------------------------------------
create table users (
    id                    bigint generated by default as identity,
    full_name             varchar(100) not null,
    email                 varchar(254) not null unique,
    password_hash         varchar(100) not null,
    role                  varchar(20) not null check (role in ('ADMIN', 'EMPLOYER', 'JOB_SEEKER')),
    enabled               boolean not null,
    company_name          varchar(120),
    company_website       varchar(200),
    company_description   varchar(1000),
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    last_login_at         timestamp(6),

    -- Brute-force lockout state (Section 4.10). Nullable on purpose, and the
    -- baseline keeps them that way rather than tightening them to NOT NULL.
    -- They were added to a User entity whose table was already populated, and
    -- ddl-auto=update cannot add a NOT NULL column to a table with rows; the
    -- entity's own comment records that. Changing the nullability here would
    -- make V1 describe a schema that the live databases - which are baselined,
    -- not rebuilt - do not actually have, and Hibernate's validate does not
    -- check nullability, so the difference would go unnoticed until something
    -- else broke. null means "has never failed a login".
    failed_login_attempts integer,
    lockout_until         timestamp(6),

    primary key (id)
);


-- ---------------------------------------------------------------------------
-- seeker_profiles - the extra fields a job seeker has and an employer does not
-- (Section 5.2). One row per seeker, created empty at registration; the
-- resume_* columns are filled in later by SeekerProfileService.uploadResume.
-- ---------------------------------------------------------------------------
create table seeker_profiles (
    id                   bigint generated by default as identity,
    user_id              bigint not null unique,
    headline             varchar(120),
    phone                varchar(15),
    location             varchar(100),
    skills               varchar(400),
    experience_years     integer not null,
    preferred_job_type   varchar(20) check (preferred_job_type in ('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT')),
    education            varchar(200),
    about                varchar(1000),
    resume_stored_name   varchar(60),
    resume_original_name varchar(150),
    resume_content_type  varchar(100),
    resume_size_bytes    bigint,
    resume_uploaded_at   timestamp(6),
    updated_at           timestamp(6),
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- jobs - one job posting (Section 5.2). `status` is the stored lifecycle of
-- Section 5.5; Live, Expired and Hidden are computed in Job.displayStatus and
-- are deliberately not columns.
-- ---------------------------------------------------------------------------
create table jobs (
    id                   bigint generated by default as identity,
    employer_id          bigint not null,
    title                varchar(120) not null,
    description          varchar(4000) not null,
    requirements         varchar(2000) not null,
    skills               varchar(400) not null,
    category             varchar(30) not null check (category in ('SOFTWARE_DEVELOPMENT', 'DATA_ANALYTICS', 'DESIGN', 'MARKETING', 'SALES', 'FINANCE', 'HUMAN_RESOURCES', 'CUSTOMER_SUPPORT', 'OPERATIONS', 'OTHER')),
    job_type             varchar(20) not null check (job_type in ('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT')),
    work_mode            varchar(20) not null check (work_mode in ('ONSITE', 'REMOTE', 'HYBRID')),
    location             varchar(100) not null,
    salary_min           integer not null,
    salary_max           integer not null,
    min_experience_years integer not null,
    openings             integer not null,
    application_deadline date not null,
    status               varchar(20) not null check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED')),
    rejection_reason     varchar(500),
    view_count           integer not null,
    created_at           timestamp(6) not null,
    updated_at           timestamp(6),
    approved_at          timestamp(6),
    closed_at            timestamp(6),
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- job_applications - one seeker's application to one job (Section 5.2). The
-- resume_* columns are a per-application copy of the seeker's resume metadata,
-- so a later profile change never rewrites history (Section 7.4).
--
-- uk_application_job_seeker is named explicitly in the entity rather than left
-- to Hibernate, because JobApplicationRepositoryTest asserts on the rule it
-- enforces: one application per seeker per job (S-F2).
-- ---------------------------------------------------------------------------
create table job_applications (
    id                    bigint generated by default as identity,
    job_id                bigint not null,
    seeker_id             bigint not null,
    status                varchar(20) not null check (status in ('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'HIRED', 'REJECTED', 'WITHDRAWN')),
    cover_letter          varchar(3000),
    resume_stored_name    varchar(60) not null,
    resume_original_name  varchar(150) not null,
    resume_content_type   varchar(100) not null,
    resume_size_bytes     bigint not null,
    internal_note         varchar(1000),
    applied_at            timestamp(6) not null,
    status_changed_at     timestamp(6),
    seeker_last_viewed_at timestamp(6),
    updated_at            timestamp(6),
    primary key (id),
    constraint uk_application_job_seeker unique (job_id, seeker_id)
);


-- ---------------------------------------------------------------------------
-- messages - one message in the thread attached to an application (Section
-- 5.2). The column is read_at, not `read`, because `read` is reserved in
-- MySQL; null means unread.
-- ---------------------------------------------------------------------------
create table messages (
    id             bigint generated by default as identity,
    application_id bigint not null,
    sender_id      bigint not null,
    recipient_id   bigint not null,
    body           varchar(2000) not null,
    sent_at        timestamp(6) not null,
    read_at        timestamp(6),
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- job_status_changes - the audit trail behind a job's status history
-- (Section 5.5). from_status is null for the very first row, which records the
-- job being created.
-- ---------------------------------------------------------------------------
create table job_status_changes (
    id          bigint generated by default as identity,
    job_id      bigint not null,
    from_status varchar(20) check (from_status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED')),
    to_status   varchar(20) not null check (to_status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED')),
    reason      varchar(500),
    actor_name  varchar(230) not null,
    actor_role  varchar(20) check (actor_role in ('ADMIN', 'EMPLOYER', 'JOB_SEEKER')),
    changed_at  timestamp(6) not null,
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- application_status_changes - the same idea for an application's status
-- history (Section 5.6), plus the note the employer showed the candidate.
-- ---------------------------------------------------------------------------
create table application_status_changes (
    id                bigint generated by default as identity,
    application_id    bigint not null,
    from_status       varchar(20) check (from_status in ('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'HIRED', 'REJECTED', 'WITHDRAWN')),
    to_status         varchar(20) not null check (to_status in ('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'HIRED', 'REJECTED', 'WITHDRAWN')),
    note_to_candidate varchar(500),
    actor_name        varchar(230) not null,
    actor_role        varchar(20) not null check (actor_role in ('ADMIN', 'EMPLOYER', 'JOB_SEEKER')),
    changed_at        timestamp(6) not null,
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- activity_logs - one row of the site-wide activity feed (Section 5.7).
-- Deliberately has NO foreign keys (Section 5.1): actor_id and target_id are
-- plain numbers, so logging a user's actions never blocks deleting that user
-- and the row still reads correctly afterwards. The foreign key section below
-- must stay silent about this table.
-- ---------------------------------------------------------------------------
create table activity_logs (
    id          bigint generated by default as identity,
    type        varchar(40) not null check (type in ('USER_REGISTERED', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_STATUS_CHANGED', 'USER_DELETED', 'JOB_POSTED', 'JOB_UPDATED', 'JOB_APPROVED', 'JOB_REJECTED', 'JOB_TAKEN_DOWN', 'JOB_CLOSED', 'JOB_REOPENED', 'JOB_DELETED', 'APPLICATION_SUBMITTED', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_WITHDRAWN', 'MESSAGE_SENT', 'PROFILE_UPDATED', 'RESUME_UPLOADED', 'SETTINGS_UPDATED')),
    actor_id    bigint,
    actor_name  varchar(230),
    actor_role  varchar(20) check (actor_role in ('ADMIN', 'EMPLOYER', 'JOB_SEEKER')),
    description varchar(500) not null,
    target_type varchar(20) check (target_type in ('USER', 'JOB', 'APPLICATION', 'SETTINGS')),
    target_id   bigint,
    ip_address  varchar(45),
    created_at  timestamp(6) not null,
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- system_settings - the single settings row, id 1 (Section 7.5). The id is
-- assigned by SettingsService.ensureDefaults, not generated, so this is the
-- one table whose primary key is not an identity column.
-- ---------------------------------------------------------------------------
create table system_settings (
    id                           bigint not null,
    site_name                    varchar(60) not null,
    announcement                 varchar(200),
    seeker_registration_open     boolean not null,
    employer_registration_open   boolean not null,
    job_approval_required        boolean not null,
    max_active_jobs_per_employer integer not null,
    max_resume_size_mb           integer not null,
    allowed_resume_types         varchar(50) not null,
    page_size                    integer not null,
    feed_refresh_seconds         integer not null,
    updated_at                   timestamp(6),
    updated_by                   varchar(100),
    primary key (id)
);


-- ---------------------------------------------------------------------------
-- Foreign keys.
--
-- The names below are Hibernate's generated hashes, copied exactly. They look
-- like noise, and a nicer scheme (fk_jobs_employer and so on) would read
-- better - but renaming them here would make V1 describe a schema that differs
-- from the live databases it is about to adopt, purely cosmetically, and the
-- adopted databases would keep the old names forever anyway. Matching what is
-- already on disk is worth more than tidiness. New tables added from V2 onward
-- should name their constraints properly (Section 10.7).
--
-- No ON DELETE clause: deletion order is the application's job, enforced in
-- the services (Section 5.8), so a stray cascade cannot quietly remove rows
-- the audit trail is supposed to keep.
-- ---------------------------------------------------------------------------
alter table seeker_profiles
    add constraint FKfuaiwjkwnqiwlgfcdh9rqblw7 foreign key (user_id) references users;

alter table jobs
    add constraint FKl3otvetpyn3n8b83eqtrp5l7i foreign key (employer_id) references users;

alter table job_applications
    add constraint FKqt4m3c9yiioi16kwsyjrl0cpl foreign key (job_id) references jobs;

alter table job_applications
    add constraint FKpgjvm2psde8cdtya6sq71duxq foreign key (seeker_id) references users;

alter table messages
    add constraint FKnqs0agypwrgvyxn8wwlnxxwru foreign key (application_id) references job_applications;

alter table messages
    add constraint FK4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references users;

alter table messages
    add constraint FKhdkwfnspwb3s60j27vpg0rpg6 foreign key (recipient_id) references users;

alter table job_status_changes
    add constraint FK2ukadxtdowrhe8gif5ck6dbm5 foreign key (job_id) references jobs;

alter table application_status_changes
    add constraint FK4lnsodh6ww8r8p4dhbuk5uqad foreign key (application_id) references job_applications;
