-- ===========================================================================
-- V2 - job_views (dated view analytics feature)
--
-- WHY THIS TABLE EXISTS ALONGSIDE Job.viewCount
-- Job.viewCount (V1) is a single running total per job: fast to read, cheap to store, and
-- already wired into every screen that shows "views" today (the E-D5 per-job table's Views
-- column and its apply-rate formula, JobStatsRow) - all all-time, because Section 7.6 says
-- so explicitly: "views are not dated". It answers exactly one question, "how many views,
-- ever," and answers it well, so this migration does not touch it.
--
-- What it cannot answer is "when": a trend line, or a funnel scoped to the same 7/30/90
-- day windows every other chart on the statistics pages already uses (util.DateBuckets).
-- That needs one row per counted view, with a timestamp - this table. The two are
-- deliberately never reconciled: nothing recomputes viewCount from a count of job_views
-- rows, or the other way round, because they answer different questions rather than being
-- two measurements of the same one, so there is nothing for them to drift out of sync
-- with. See domain.JobView and JobSearchService#recordView for the reasoning in full, and
-- the feature's delivery report for the three decisions this migration embodies (keep
-- viewCount as-is; a stricter, additive write path for this table alone to bound its
-- growth and keep out obvious bot/scanner noise; retention left for a future sweep).
--
-- WHICH VIEWS BECOME A ROW HERE
-- Only the same views that already bump viewCount today (JobSearchService#recordView: the
-- job is Live, the viewer is neither its own employer nor an admin, and this is the first
-- time the current HTTP session has viewed this job) AND that pass util.BotDetector's
-- lightweight "does this look like a person" check on the request's User-Agent. viewCount
-- keeps counting everything it always has, completely unchanged by this feature.
--
-- SHAPE AND NAMING
-- Same shared form V1 uses throughout (Section 10.7): `bigint generated by default as
-- identity` for the key, `timestamp(6)` for the LocalDateTime column, no ON DELETE clause
-- (deletion order is enforced in the services, V1's own foreign-key section). The
-- constraint is given a proper name, fk_job_views_job, rather than one of V1's copied
-- generated hashes - Section 10.7's own rule for every migration from V2 onward.
--
-- NO SECONDARY INDEX, ON PURPOSE, FOR NOW
-- job_id and viewed_at are exactly the columns every query here filters on, and an index
-- covering both would help at real scale - but V1 does not add a manual index to any of
-- its own foreign-key columns either (not even job_applications.job_id or
-- messages.application_id, both queried constantly), so this table follows the same
-- baseline posture rather than introducing a one-off exception. It is called out as future
-- work in the delivery report alongside retention, which is the more pressing of the two:
-- an index keeps a big table's queries fast, but only deleting old rows keeps it small.
-- ===========================================================================

create table job_views (
    id        bigint generated by default as identity,
    job_id    bigint not null,
    viewed_at timestamp(6) not null,
    primary key (id)
);

alter table job_views
    add constraint fk_job_views_job foreign key (job_id) references jobs;
