-- ===========================================================================
-- V3 - password_reset_tokens (Section 16 #1 / I-17: self-service password
-- reset by emailed token, replacing "an admin sets a new password by hand" as
-- the only recovery path).
--
-- Unlike V1, this table was never built by ddl-auto=update, so there is no
-- pre-existing data to match column-for-column and no generated foreign-key
-- hash to preserve - this migration names its own constraint, following the
-- "how a feature adds a migration" recipe of Section 10.7 rather than V1's
-- "adopt what is already there" one.
--
-- WHAT IS STORED, AND WHY tokenHash RATHER THAN THE TOKEN ITSELF
-- The raw, emailed token is a bearer credential: anyone who has it can reset
-- the account's password without knowing the old one, which makes a raw token
-- sitting in this table exactly as sensitive as a plaintext password would be
-- in `users.password_hash`. So only a SHA-256 hash of it is ever written here
-- (PasswordResetService); the raw value exists for a few moments in memory
-- and inside the one email that is sent, and nowhere else. SHA-256, not
-- BCrypt: BCrypt's cost factor defends a LOW-entropy human-chosen secret
-- against offline guessing, which is irrelevant to a 256-bit SecureRandom
-- value that is already impossible to guess; what BCrypt's per-hash salt
-- would cost here is the ability to look the token up directly by an indexed
-- equality match (a salted hash cannot be queried that way; every row would
-- have to be reloaded and compared by hand), which is the only thing this
-- table actually needs to do.
--
-- token_hash is 64 characters: SHA-256's output is exactly 32 bytes, and
-- HexFormat renders that as 64 hex characters every time, so there is no
-- variable-length padding concern the way there is for the composed columns
-- of Section 5.2's exception table.
--
-- used_at is nullable and is what makes a token single-use (hard requirement
-- 4): null means unused; PasswordResetService.resetPassword sets it the
-- moment a token is consumed and PasswordResetToken.isUsable(now) then
-- refuses it a second time, the same "one boolean-ish column decides" shape
-- JobApplication.seeker_last_viewed_at and messages.read_at already use for
-- "has this happened yet".
-- ===========================================================================

create table password_reset_tokens (
    id          bigint generated by default as identity,
    user_id     bigint not null,
    token_hash  varchar(64) not null unique,
    created_at  timestamp(6) not null,
    expires_at  timestamp(6) not null,
    used_at     timestamp(6),
    primary key (id)
);

-- No ON DELETE clause, matching every other foreign key in this project
-- (Section 10.7/V1): a user with outstanding reset tokens is deleted through
-- UserService, which is free to remove or ignore this table's rows the same
-- deliberate way Section 5.8 already lists for every other child table.
alter table password_reset_tokens
    add constraint fk_password_reset_tokens_user foreign key (user_id) references users;
