-- ===========================================================================
-- V5 - saved_jobs and job_alert_subscriptions (Section 16 future-work item 5:
-- "saved or bookmarked jobs, job alerts", now built).
--
-- Two independent tables for the two halves of the feature - see SavedJob and
-- JobAlertSubscription's own class comments for why each is its own table rather than a
-- field on SeekerProfile or User (both of which are frozen at foundation-v1, 11.3 contract
-- item 1). Written the same way V2/V3 were (10.7 "how a feature adds a migration"): plain
-- SQL that runs unchanged on H2 and PostgreSQL, identity keys, timestamp(6) for
-- LocalDateTime, and constraints named properly instead of left to a generated hash.
--
-- saved_jobs
-- One row per (seeker, job) bookmark. uk_saved_job_seeker_job is the same "one X per
-- seeker per job" shape V1's uk_application_job_seeker already uses for applications -
-- SavedJobService relies on it being impossible to save the same job twice.
--
-- job_alert_subscriptions
-- One row per seeker who has ever opted in to the weekly digest, toggled by `enabled`
-- rather than deleted on opt-out, so `unsubscribe_token` keeps working across an
-- opt-out/opt-in cycle (a seeker re-enabling alerts must not silently break the
-- unsubscribe link sitting in every digest they already received). Unlike
-- password_reset_tokens.token_hash, unsubscribe_token stores the raw, 256-bit random value
-- rather than a hash of it - JobAlertSubscription's own comment explains why that is the
-- deliberately correct choice here (a reusable, low-severity capability, not a
-- password-equivalent secret) rather than a shortcut.
--
-- WHY NEITHER TABLE HAS AN ON DELETE CLAUSE, AND WHERE THE CLEANUP HAPPENS INSTEAD
-- Same rule as every table since V1 (10.7, V1's own foreign-key section): deletion order is
-- enforced in the services, not the schema, so a stray cascade can never quietly remove a
-- row some other feature still needed. Concretely: JobService.delete() now also clears a
-- deleted job's saved_jobs rows before deleting the Job itself (mirroring how it already
-- clears JobStatusChange rows first), and UserService.delete() now also clears a deleted
-- user's saved_jobs and job_alert_subscriptions rows (mirroring the existing
-- passwordResetTokenRepository.deleteByUser_Id call right next to it, and for the identical
-- reason - see that call's own comment). Without this, deleting a job or user that this
-- feature had touched would fail with the generic "related data exists" message even though
-- neither is counted as a blocking dependency (Section 5.8's table already treats an
-- outstanding password-reset token the same way: cleaned up silently, never a reason to
-- refuse a delete).
-- ===========================================================================

create table saved_jobs (
    id        bigint generated by default as identity,
    seeker_id bigint not null,
    job_id    bigint not null,
    saved_at  timestamp(6) not null,
    primary key (id),
    constraint uk_saved_job_seeker_job unique (seeker_id, job_id)
);

alter table saved_jobs
    add constraint fk_saved_jobs_seeker foreign key (seeker_id) references users;

alter table saved_jobs
    add constraint fk_saved_jobs_job foreign key (job_id) references jobs;


create table job_alert_subscriptions (
    id                bigint generated by default as identity,
    user_id           bigint not null unique,
    enabled           boolean not null,
    unsubscribe_token varchar(43) not null unique,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    last_sent_at      timestamp(6),
    primary key (id)
);

alter table job_alert_subscriptions
    add constraint fk_job_alert_subscriptions_user foreign key (user_id) references users;
