-- ===========================================================================
-- V6 - interviews (interview scheduling feature, built on top of the existing
-- ApplicationStatus.INTERVIEW stage of Section 5.6).
--
-- Purely additive: one new table and one new foreign key, nothing altered and
-- nothing dropped. That is deliberate and not just tidiness - V4 and V5 belong
-- to features being written in parallel, so anything this file did to an
-- EXISTING object would have to reason about a version of the schema it cannot
-- see. In particular it does NOT touch the check constraint on
-- activity_logs.type: adding an INTERVIEW_SCHEDULED / _RESCHEDULED /
-- _CANCELLED ActivityType would mean dropping and recreating that constraint
-- (Section 10.7's "adding a value to an enum" recipe), and V1 leaves it
-- UNNAMED, so the name to drop is one H2 and PostgreSQL each invent for
-- themselves - exactly the kind of "one migration, two databases" split
-- Section 10.7 rejected. Interview events are therefore not written to the
-- activity feed; the APPLICATION_STATUS_CHANGED row for the move to Interview
-- already marks the stage, and the candidate's own view of the appointment is
-- the interviews row itself. Called out in the delivery report as future work.
--
-- WHY ONE ROW PER APPLICATION (uk_interview_application)
-- Rescheduling updates the row in place and cancelling sets status =
-- 'CANCELLED' rather than deleting it, so "what, if anything, is arranged for
-- this application?" is always one row, and a cancelled appointment is still
-- visible to the candidate instead of silently vanishing from their page. The
-- constraint is named here rather than left to Hibernate for the same reason
-- V1 names uk_application_job_seeker: the rule it enforces is asserted on
-- directly by InterviewSchedulingTest.
--
-- WHY THERE IS BOTH scheduled_at AND time_zone
-- scheduled_at is the wall-clock time the employer typed, stored unchanged, in
-- the same timestamp(6) form every other LocalDateTime column in this schema
-- uses. time_zone is the ZoneId id that wall clock belongs to, taken from the
-- injected Clock at the moment of scheduling, and the two are always read
-- together: nothing ever converts scheduled_at, it is rendered verbatim with
-- the zone named beside it (domain.Interview#getWhenText, whose comment has the
-- full reasoning). A bare local timestamp would be the ordinary choice here and
-- is wrong for this one table: every other time in this schema is a record of
-- something that already happened, where an unstated zone at worst misreports
-- history by a few hours, whereas this one is an appointment a human has to
-- turn up to, and the same digits mean different moments to the employer and
-- the candidate unless the zone travels with them.
--
-- previous_scheduled_at and reschedule_count are the whole of the history kept
-- for an appointment that moved - enough for the candidate's page to say "moved
-- from 21 Sep 2026, 10:00 AM IST" so an old calendar entry can be recognised
-- and deleted. Deliberately not a job_status_changes-style history table: a
-- superseded interview slot stops mattering once the new one is agreed, unlike
-- a status decision, which is accountability that has to survive forever.
--
-- SHAPE AND NAMING follow Section 10.7's shared form, same as V2 and V3:
-- `bigint generated by default as identity` for the key, `varchar(n)` plus a
-- `check (... in (...))` for the two enum columns, `timestamp(6)` for every
-- LocalDateTime, `integer not null` for the primitive int, and a properly named
-- foreign key (fk_interviews_application) with no ON DELETE clause - deletion
-- order is enforced in the services, exactly as V1's own foreign-key section
-- and Section 5.8 describe.
-- ===========================================================================

create table interviews (
    id                    bigint generated by default as identity,
    application_id        bigint not null,
    status                varchar(20) not null check (status in ('SCHEDULED', 'CANCELLED')),
    mode                  varchar(20) not null check (mode in ('PHONE', 'VIDEO', 'ON_SITE')),
    scheduled_at          timestamp(6) not null,
    time_zone             varchar(60) not null,
    location              varchar(300),
    notes                 varchar(1000),
    previous_scheduled_at timestamp(6),
    reschedule_count      integer not null,
    cancellation_reason   varchar(500),
    cancelled_at          timestamp(6),
    created_at            timestamp(6) not null,
    updated_at            timestamp(6) not null,
    primary key (id),
    constraint uk_interview_application unique (application_id)
);

alter table interviews
    add constraint fk_interviews_application foreign key (application_id) references job_applications;
